# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "aschmere/hello_world:latest"
  amd64: "aschmere/hello_world:latest"
  armhf: "aschmere/hello_world:latest"
  armv7: "aschmere/hello_world:latest"
  i386: "aschmere/hello_world:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Hello World."
  org.opencontainers.image.description: "Hello World"
args:
  TEMPIO_VERSION: "2021.09.0"
