name: Hello World
version: 1.1.0
slug: hello_world
description: My first Home Assistant add-on.
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  5123/tcp: 5123
options:
  greeting: "Hello, Home Assistant!"
schema:
  greeting: "str?"
image: "aschmere/hello_world"
init: false


